ALTER TABLE accounts ALTER COLUMN active TYPE VARCHAR(20)
    USING CASE WHEN active THEN 'ACTIVE' ELSE 'SUSPENDED' END;
ALTER TABLE accounts ALTER COLUMN active SET NOT NULL;
ALTER TABLE accounts RENAME COLUMN active TO status;
