spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/bank_db
    username: ${DB_USERNAME:bank_user}
    password: ${DB_PASSWORD:bank_password}
    hikari:
      read-only: false

jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  allow-default-secret: true
