-- V29__create_ledger_entries.sql
-- Double-entry journal for every balance movement. accounts.balance stays the
-- operational balance; ledger_entries is the append-only evidence that every
-- business operation nets to zero:
--   SELECT transaction_ref, SUM(CASE WHEN direction = 'DEBIT' THEN -amount ELSE amount END)
--   FROM ledger_entries GROUP BY transaction_ref HAVING SUM(...) <> 0
-- must always return zero rows. The application writes both legs of an
-- operation with one transaction_ref inside the same local transaction as the
-- balance mutation, so a failed leg rolls the money movement back.
-- New table: no legacy rows, plain inline foreign key (unlike V24 restores).

CREATE TABLE ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_ref VARCHAR(36) NOT NULL,
    account_id BIGINT NOT NULL REFERENCES accounts (id) ON DELETE RESTRICT,
    direction VARCHAR(6) NOT NULL,
    amount NUMERIC(38,2) NOT NULL,
    currency VARCHAR(3) NOT NULL,
    balance_after NUMERIC(38,2) NOT NULL,
    business_at TIMESTAMP(6) NOT NULL,
    created_at TIMESTAMP(6) NOT NULL,
    created_by VARCHAR(255),
    updated_at TIMESTAMP(6),
    updated_by VARCHAR(255),
    CONSTRAINT chk_ledger_direction CHECK (direction IN ('DEBIT', 'CREDIT')),
    CONSTRAINT chk_ledger_amount CHECK (amount > 0)
);

-- Double-entry check per operation (legs of one ref must net to zero).
CREATE INDEX IF NOT EXISTS idx_ledger_transaction_ref
    ON ledger_entries (transaction_ref);

-- Per-account movement history (reconciliation scans).
CREATE INDEX IF NOT EXISTS idx_ledger_account_business
    ON ledger_entries (account_id, business_at DESC);
