-- scripts/audit_partition_cutover.sql
--
-- ONE-TIME maintenance-window cutover: converts audit_logs to native
-- declarative RANGE partitioning on "timestamp" (monthly-by-half-year
-- windows, see below). Implements docs/decisions/partitioning.md steps 2-3
-- without a pg_partman dependency.
--
-- HOW TO RUN (maintenance window, writes drained per the ADR):
--   psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f scripts/audit_partition_cutover.sql
--
-- REQUIREMENTS: Flyway V46 applied ("timestamp" is TIMESTAMPTZ; the script
-- fails fast otherwise). Nothing references audit_logs (no FKs/views/triggers
-- by design: V34 keeps actor_user_id FK-free).
--
-- SAFETY:
--   * Single transaction: the rename swap is atomic; concurrent writes block
--     briefly on ACCESS EXCLUSIVE instead of hitting a half-moved table.
--   * Legacy table is kept as audit_logs_legacy for verification; drop it
--     explicitly (see bottom) only after the app has written + read post-swap.
--   * Identity sequence is restarted past max(id) so new rows never collide
--     with backfilled ids.
--   * A DEFAULT partition catches any instant outside the pre-created ranges,
--     so inserts never fail while the next window is being added (run
--     scripts/ensure_audit_partition.sql quarterly from the runbook).
--   * Post-cutover, DELETE retention keeps working (cross-partition); the
--     follow-up is switching it to DROP PARTITION (instant).

SET lock_timeout = '30s';
SET statement_timeout = '30min';

BEGIN;

-- 0. Preconditions.
DO $$
BEGIN
    IF to_regclass('public.audit_logs') IS NULL THEN
        RAISE EXCEPTION 'audit_logs missing: nothing to convert';
    END IF;
    IF (SELECT relkind FROM pg_class WHERE oid = to_regclass('public.audit_logs')) = 'p' THEN
        RAISE EXCEPTION 'audit_logs is already partitioned: cutover already ran';
    END IF;
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns
                   WHERE table_schema = 'public' AND table_name = 'audit_logs'
                     AND column_name = 'timestamp' AND udt_name = 'timestamptz') THEN
        RAISE EXCEPTION 'audit_logs.timestamp is not TIMESTAMPTZ: apply Flyway V46 first';
    END IF;
END $$;

-- 1. Partitioned parent. Column order matches the legacy table so the
--    backfill can use an explicit column list; PK must include the partition
--    key (native-partitioning rule), hence ("timestamp", id).
CREATE TABLE audit_logs_new (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    "timestamp" TIMESTAMPTZ NOT NULL,
    details TEXT NOT NULL,
    action "AuditAction" NOT NULL,
    username VARCHAR(255) NOT NULL,
    actor_user_id BIGINT,
    CONSTRAINT audit_logs_new_pkey PRIMARY KEY ("timestamp", id)
) PARTITION BY RANGE ("timestamp");

-- 2. Pre-created ranges: full history + half-year windows into 2028.
--    Anything outside lands in the DEFAULT partition (never an insert error).
--    Names are half-year aligned (pYYYYh1/h2) so the quarterly
--    ensure_audit_partition.sql never overlaps them.
CREATE TABLE audit_logs_past PARTITION OF audit_logs_new
    FOR VALUES FROM (MINVALUE) TO ('2026-07-01');
CREATE TABLE audit_logs_p2026h2 PARTITION OF audit_logs_new
    FOR VALUES FROM ('2026-07-01') TO ('2027-01-01');
CREATE TABLE audit_logs_p2027h1 PARTITION OF audit_logs_new
    FOR VALUES FROM ('2027-01-01') TO ('2027-07-01');
CREATE TABLE audit_logs_p2027h2 PARTITION OF audit_logs_new
    FOR VALUES FROM ('2027-07-01') TO ('2028-01-01');
CREATE TABLE audit_logs_default PARTITION OF audit_logs_new DEFAULT;

-- 3. Backfill (explicit columns: legacy order is id, timestamp, details,
--    action, username, actor_user_id).
INSERT INTO audit_logs_new (id, "timestamp", details, action, username, actor_user_id)
    SELECT id, "timestamp", details, action, username, actor_user_id FROM audit_logs;

-- 4. Atomic swap.
ALTER TABLE audit_logs RENAME TO audit_logs_legacy;
ALTER TABLE audit_logs_new RENAME TO audit_logs;

-- 5. Restart the new identity past the backfilled max (empty table -> 1).
SELECT setval(pg_get_serial_sequence('audit_logs', 'id'),
    COALESCE((SELECT max(id) FROM audit_logs), 0));

-- 6. Recreate the query-surface indexes on the parent (auto-propagate to
--    every partition). Suffixed _new: the legacy table (renamed below, kept
--    for verification) still owns the canonical names; the finalize script
--    drops the legacy table and renames these after post-swap reads are green.
CREATE INDEX idx_audit_logs_timestamp_new ON audit_logs ("timestamp" DESC);
CREATE INDEX idx_audit_logs_username_new ON audit_logs (username);
CREATE INDEX idx_audit_logs_timestamp_id_new ON audit_logs ("timestamp" DESC, id DESC);
CREATE INDEX idx_audit_logs_actor_timestamp_new
    ON audit_logs (actor_user_id, "timestamp" DESC, id DESC);

COMMIT;

-- 7. Verify BEFORE finalizing (counts, PK, partitions).
SELECT count(*) AS new_rows FROM audit_logs;
SELECT count(*) AS legacy_rows FROM audit_logs_legacy;
SELECT tablename FROM pg_tables WHERE schemaname = 'public' AND tablename LIKE 'audit_logs\_p%';
SELECT indexname FROM pg_indexes WHERE schemaname = 'public' AND tablename = 'audit_logs';
ANALYZE audit_logs;

-- 8. After the app has written + read post-swap (new rows land in the current
--    partition; admin listing + per-actor lookup green), run
--    scripts/audit_partition_finalize.sql: it drops the legacy copy and
--    renames the _new indexes to their canonical names. Then switch retention
--    to DROP PARTITION (instant) per partitioning.md step 4, and schedule
--    scripts/ensure_audit_partition.sql quarterly.
