package com.bank.app.common.domain.exception;

public enum ErrorCode {
    GENERAL_INTERNAL_ERROR,
    SECURITY_BACKEND_UNAVAILABLE,
    VALIDATION_FAILED,
    INVALID_ARGUMENT,
    INVALID_FORMAT,
    INVALID_ENUM_VALUE,
    AUTHENTICATION_FAILED,
    ACCESS_DENIED,
    RESOURCE_NOT_FOUND,
    METHOD_NOT_ALLOWED,
    OPTIMISTIC_LOCK_CONFLICT,
    UNIQUE_CONSTRAINT_VIOLATION,
    DB_INTEGRITY_VIOLATION,
    CONCURRENT_REQUEST,
    RATE_LIMIT_EXCEEDED,
    UNSUPPORTED_MEDIA_TYPE;

    public String code() {
        return name();
    }
}
